package ht.ihsi.rgph.mobile.epc.Backend.Entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_batiment".
 */
public class Batiment {

    private Long batimentId;
    private String deptId;
    private String comId;
    private String vqseId;
    private String sdeId;
    private Short zone;
    private String disctrictId;
    private String qhabitation;
    private String qlocalite;
    private String qadresse;
    private String qrec;
    private String qepc;
    private Short qb1Type;
    private Short qb2StatutOccupation;
    private Short qb3NbreLogeIndividuel;
    private Short statut;
    private String dateEnvoi;
    private Boolean isValidated;
    private Boolean isSynchroToAppSup;
    private Boolean isSynchroToCentrale;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isFieldAllFilled;
    private Boolean isContreEnqueteMade;
    private String latitude;
    private String longitude;
    private String codeAgentRecenceur;

    public Batiment() {
    }

    public Batiment(Long batimentId) {
        this.batimentId = batimentId;
    }

    public Batiment(Long batimentId, String deptId, String comId, String vqseId, String sdeId, Short zone, String disctrictId, String qhabitation, String qlocalite, String qadresse, String qrec, String qepc, Short qb1Type, Short qb2StatutOccupation, Short qb3NbreLogeIndividuel, Short statut, String dateEnvoi, Boolean isValidated, Boolean isSynchroToAppSup, Boolean isSynchroToCentrale, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isFieldAllFilled, Boolean isContreEnqueteMade, String latitude, String longitude, String codeAgentRecenceur) {
        this.batimentId = batimentId;
        this.deptId = deptId;
        this.comId = comId;
        this.vqseId = vqseId;
        this.sdeId = sdeId;
        this.zone = zone;
        this.disctrictId = disctrictId;
        this.qhabitation = qhabitation;
        this.qlocalite = qlocalite;
        this.qadresse = qadresse;
        this.qrec = qrec;
        this.qepc = qepc;
        this.qb1Type = qb1Type;
        this.qb2StatutOccupation = qb2StatutOccupation;
        this.qb3NbreLogeIndividuel = qb3NbreLogeIndividuel;
        this.statut = statut;
        this.dateEnvoi = dateEnvoi;
        this.isValidated = isValidated;
        this.isSynchroToAppSup = isSynchroToAppSup;
        this.isSynchroToCentrale = isSynchroToCentrale;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isFieldAllFilled = isFieldAllFilled;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.latitude = latitude;
        this.longitude = longitude;
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getComId() {
        return comId;
    }

    public void setComId(String comId) {
        this.comId = comId;
    }

    public String getVqseId() {
        return vqseId;
    }

    public void setVqseId(String vqseId) {
        this.vqseId = vqseId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getZone() {
        return zone;
    }

    public void setZone(Short zone) {
        this.zone = zone;
    }

    public String getDisctrictId() {
        return disctrictId;
    }

    public void setDisctrictId(String disctrictId) {
        this.disctrictId = disctrictId;
    }

    public String getQhabitation() {
        return qhabitation;
    }

    public void setQhabitation(String qhabitation) {
        this.qhabitation = qhabitation;
    }

    public String getQlocalite() {
        return qlocalite;
    }

    public void setQlocalite(String qlocalite) {
        this.qlocalite = qlocalite;
    }

    public String getQadresse() {
        return qadresse;
    }

    public void setQadresse(String qadresse) {
        this.qadresse = qadresse;
    }

    public String getQrec() {
        return qrec;
    }

    public void setQrec(String qrec) {
        this.qrec = qrec;
    }

    public String getQepc() {
        return qepc;
    }

    public void setQepc(String qepc) {
        this.qepc = qepc;
    }

    public Short getQb1Type() {
        return qb1Type;
    }

    public void setQb1Type(Short qb1Type) {
        this.qb1Type = qb1Type;
    }

    public Short getQb2StatutOccupation() {
        return qb2StatutOccupation;
    }

    public void setQb2StatutOccupation(Short qb2StatutOccupation) {
        this.qb2StatutOccupation = qb2StatutOccupation;
    }

    public Short getQb3NbreLogeIndividuel() {
        return qb3NbreLogeIndividuel;
    }

    public void setQb3NbreLogeIndividuel(Short qb3NbreLogeIndividuel) {
        this.qb3NbreLogeIndividuel = qb3NbreLogeIndividuel;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public String getDateEnvoi() {
        return dateEnvoi;
    }

    public void setDateEnvoi(String dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public Boolean getIsSynchroToAppSup() {
        return isSynchroToAppSup;
    }

    public void setIsSynchroToAppSup(Boolean isSynchroToAppSup) {
        this.isSynchroToAppSup = isSynchroToAppSup;
    }

    public Boolean getIsSynchroToCentrale() {
        return isSynchroToCentrale;
    }

    public void setIsSynchroToCentrale(Boolean isSynchroToCentrale) {
        this.isSynchroToCentrale = isSynchroToCentrale;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

}
