package ht.ihsi.rgph.mobile.epc.Backend.Entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_logement".
 */
public class Logement {

    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short qlin1NumeroOrdre;
    private Short qlin3StatutOccupation;
    private Short qlin2TypeLogement;
    private Short qlin4NbreIndividuDepense;
    private Short qlin5NbreTotalMenage;
    private Short statut;
    private Boolean isValidated;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isContreEnqueteMade;
    private Short nbrTentative;
    private String codeAgentRecenceur;

    public Logement() {
    }

    public Logement(Long logeId) {
        this.logeId = logeId;
    }

    public Logement(Long logeId, Long batimentId, String sdeId, Short qlin1NumeroOrdre, Short qlin3StatutOccupation, Short qlin2TypeLogement, Short qlin4NbreIndividuDepense, Short qlin5NbreTotalMenage, Short statut, Boolean isValidated, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isContreEnqueteMade, Short nbrTentative, String codeAgentRecenceur) {
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.qlin1NumeroOrdre = qlin1NumeroOrdre;
        this.qlin3StatutOccupation = qlin3StatutOccupation;
        this.qlin2TypeLogement = qlin2TypeLogement;
        this.qlin4NbreIndividuDepense = qlin4NbreIndividuDepense;
        this.qlin5NbreTotalMenage = qlin5NbreTotalMenage;
        this.statut = statut;
        this.isValidated = isValidated;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.nbrTentative = nbrTentative;
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQlin1NumeroOrdre() {
        return qlin1NumeroOrdre;
    }

    public void setQlin1NumeroOrdre(Short qlin1NumeroOrdre) {
        this.qlin1NumeroOrdre = qlin1NumeroOrdre;
    }

    public Short getQlin3StatutOccupation() {
        return qlin3StatutOccupation;
    }

    public void setQlin3StatutOccupation(Short qlin3StatutOccupation) {
        this.qlin3StatutOccupation = qlin3StatutOccupation;
    }

    public Short getQlin2TypeLogement() {
        return qlin2TypeLogement;
    }

    public void setQlin2TypeLogement(Short qlin2TypeLogement) {
        this.qlin2TypeLogement = qlin2TypeLogement;
    }

    public Short getQlin4NbreIndividuDepense() {
        return qlin4NbreIndividuDepense;
    }

    public void setQlin4NbreIndividuDepense(Short qlin4NbreIndividuDepense) {
        this.qlin4NbreIndividuDepense = qlin4NbreIndividuDepense;
    }

    public Short getQlin5NbreTotalMenage() {
        return qlin5NbreTotalMenage;
    }

    public void setQlin5NbreTotalMenage(Short qlin5NbreTotalMenage) {
        this.qlin5NbreTotalMenage = qlin5NbreTotalMenage;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public Short getNbrTentative() {
        return nbrTentative;
    }

    public void setNbrTentative(Short nbrTentative) {
        this.nbrTentative = nbrTentative;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

}
