package ht.ihsi.rgph.mobile.epc.Backend.Entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.rgph.mobile.epc.Backend.Entities.Logement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tbl_logement".
*/
public class LogementDao extends AbstractDao<Logement, Long> {

    public static final String TABLENAME = "tbl_logement";

    /**
     * Properties of entity Logement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property LogeId = new Property(0, Long.class, "logeId", true, "logeId");
        public final static Property BatimentId = new Property(1, Long.class, "batimentId", false, "batimentId");
        public final static Property SdeId = new Property(2, String.class, "sdeId", false, "sdeId");
        public final static Property Qlin1NumeroOrdre = new Property(3, Short.class, "qlin1NumeroOrdre", false, "qlin1NumeroOrdre");
        public final static Property Qlin3StatutOccupation = new Property(4, Short.class, "qlin3StatutOccupation", false, "qlin3StatutOccupation");
        public final static Property Qlin2TypeLogement = new Property(5, Short.class, "qlin2TypeLogement", false, "qlin2TypeLogement");
        public final static Property Qlin4NbreIndividuDepense = new Property(6, Short.class, "qlin4NbreIndividuDepense", false, "qlin4NbreIndividuDepense");
        public final static Property Qlin5NbreTotalMenage = new Property(7, Short.class, "qlin5NbreTotalMenage", false, "qlin5NbreTotalMenage");
        public final static Property Statut = new Property(8, Short.class, "statut", false, "statut");
        public final static Property IsValidated = new Property(9, Boolean.class, "isValidated", false, "isValidated");
        public final static Property IsFieldAllFilled = new Property(10, Boolean.class, "isFieldAllFilled", false, "isFieldAllFilled");
        public final static Property DateDebutCollecte = new Property(11, String.class, "dateDebutCollecte", false, "dateDebutCollecte");
        public final static Property DateFinCollecte = new Property(12, String.class, "dateFinCollecte", false, "dateFinCollecte");
        public final static Property DureeSaisie = new Property(13, Integer.class, "dureeSaisie", false, "dureeSaisie");
        public final static Property IsContreEnqueteMade = new Property(14, Boolean.class, "isContreEnqueteMade", false, "isContreEnqueteMade");
        public final static Property NbrTentative = new Property(15, Short.class, "nbrTentative", false, "nbrTentative");
        public final static Property CodeAgentRecenceur = new Property(16, String.class, "codeAgentRecenceur", false, "codeAgentRecenceur");
    };


    public LogementDao(DaoConfig config) {
        super(config);
    }
    
    public LogementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tbl_logement\" (" + //
                "\"logeId\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: logeId
                "\"batimentId\" INTEGER," + // 1: batimentId
                "\"sdeId\" TEXT," + // 2: sdeId
                "\"qlin1NumeroOrdre\" INTEGER," + // 3: qlin1NumeroOrdre
                "\"qlin3StatutOccupation\" INTEGER," + // 4: qlin3StatutOccupation
                "\"qlin2TypeLogement\" INTEGER," + // 5: qlin2TypeLogement
                "\"qlin4NbreIndividuDepense\" INTEGER," + // 6: qlin4NbreIndividuDepense
                "\"qlin5NbreTotalMenage\" INTEGER," + // 7: qlin5NbreTotalMenage
                "\"statut\" INTEGER," + // 8: statut
                "\"isValidated\" INTEGER," + // 9: isValidated
                "\"isFieldAllFilled\" INTEGER," + // 10: isFieldAllFilled
                "\"dateDebutCollecte\" TEXT," + // 11: dateDebutCollecte
                "\"dateFinCollecte\" TEXT," + // 12: dateFinCollecte
                "\"dureeSaisie\" INTEGER," + // 13: dureeSaisie
                "\"isContreEnqueteMade\" INTEGER," + // 14: isContreEnqueteMade
                "\"nbrTentative\" INTEGER," + // 15: nbrTentative
                "\"codeAgentRecenceur\" TEXT);"); // 16: codeAgentRecenceur
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tbl_logement\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Logement entity) {
        stmt.clearBindings();
 
        Long logeId = entity.getLogeId();
        if (logeId != null) {
            stmt.bindLong(1, logeId);
        }
 
        Long batimentId = entity.getBatimentId();
        if (batimentId != null) {
            stmt.bindLong(2, batimentId);
        }
 
        String sdeId = entity.getSdeId();
        if (sdeId != null) {
            stmt.bindString(3, sdeId);
        }
 
        Short qlin1NumeroOrdre = entity.getQlin1NumeroOrdre();
        if (qlin1NumeroOrdre != null) {
            stmt.bindLong(4, qlin1NumeroOrdre);
        }
 
        Short qlin3StatutOccupation = entity.getQlin3StatutOccupation();
        if (qlin3StatutOccupation != null) {
            stmt.bindLong(5, qlin3StatutOccupation);
        }
 
        Short qlin2TypeLogement = entity.getQlin2TypeLogement();
        if (qlin2TypeLogement != null) {
            stmt.bindLong(6, qlin2TypeLogement);
        }
 
        Short qlin4NbreIndividuDepense = entity.getQlin4NbreIndividuDepense();
        if (qlin4NbreIndividuDepense != null) {
            stmt.bindLong(7, qlin4NbreIndividuDepense);
        }
 
        Short qlin5NbreTotalMenage = entity.getQlin5NbreTotalMenage();
        if (qlin5NbreTotalMenage != null) {
            stmt.bindLong(8, qlin5NbreTotalMenage);
        }
 
        Short statut = entity.getStatut();
        if (statut != null) {
            stmt.bindLong(9, statut);
        }
 
        Boolean isValidated = entity.getIsValidated();
        if (isValidated != null) {
            stmt.bindLong(10, isValidated ? 1L: 0L);
        }
 
        Boolean isFieldAllFilled = entity.getIsFieldAllFilled();
        if (isFieldAllFilled != null) {
            stmt.bindLong(11, isFieldAllFilled ? 1L: 0L);
        }
 
        String dateDebutCollecte = entity.getDateDebutCollecte();
        if (dateDebutCollecte != null) {
            stmt.bindString(12, dateDebutCollecte);
        }
 
        String dateFinCollecte = entity.getDateFinCollecte();
        if (dateFinCollecte != null) {
            stmt.bindString(13, dateFinCollecte);
        }
 
        Integer dureeSaisie = entity.getDureeSaisie();
        if (dureeSaisie != null) {
            stmt.bindLong(14, dureeSaisie);
        }
 
        Boolean isContreEnqueteMade = entity.getIsContreEnqueteMade();
        if (isContreEnqueteMade != null) {
            stmt.bindLong(15, isContreEnqueteMade ? 1L: 0L);
        }
 
        Short nbrTentative = entity.getNbrTentative();
        if (nbrTentative != null) {
            stmt.bindLong(16, nbrTentative);
        }
 
        String codeAgentRecenceur = entity.getCodeAgentRecenceur();
        if (codeAgentRecenceur != null) {
            stmt.bindString(17, codeAgentRecenceur);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Logement readEntity(Cursor cursor, int offset) {
        Logement entity = new Logement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // logeId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // batimentId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sdeId
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3), // qlin1NumeroOrdre
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4), // qlin3StatutOccupation
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5), // qlin2TypeLogement
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6), // qlin4NbreIndividuDepense
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7), // qlin5NbreTotalMenage
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8), // statut
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // isValidated
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // isFieldAllFilled
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // dateDebutCollecte
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // dateFinCollecte
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // dureeSaisie
            cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0, // isContreEnqueteMade
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15), // nbrTentative
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16) // codeAgentRecenceur
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Logement entity, int offset) {
        entity.setLogeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBatimentId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSdeId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQlin1NumeroOrdre(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3));
        entity.setQlin3StatutOccupation(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4));
        entity.setQlin2TypeLogement(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5));
        entity.setQlin4NbreIndividuDepense(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6));
        entity.setQlin5NbreTotalMenage(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7));
        entity.setStatut(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8));
        entity.setIsValidated(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setIsFieldAllFilled(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setDateDebutCollecte(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDateFinCollecte(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDureeSaisie(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setIsContreEnqueteMade(cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0);
        entity.setNbrTentative(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15));
        entity.setCodeAgentRecenceur(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Logement entity, long rowId) {
        entity.setLogeId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Logement entity) {
        if(entity != null) {
            return entity.getLogeId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
